application: snail-prod
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.application
  login: required
  secure: always

- url: /_ah/spi/.*
  script: apis.hygie_api.application

- url: /.*
  script: main.application
  secure: always


error_handlers:
- file: templates/500.html


builtins:
- appstats: off


libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest
